apiVersion: v1
kind: Pod
metadata:
  name: stdoutlat
spec:
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: stdoutlat
    image: golang:1-bookworm
    command: [ "/bin/sh" ]
    args: ["-c", "git clone https://github.com/rtreffer/experiments.git ; cd experiments ; go run stdoutlat/cmd/main.go --frequency 50 --history.length 50000 --latency.interval 10"]
    resources:
      requests:
        cpu: "1.0"
        memory: "64Mi"
      limits: {}
  - name: sleep1
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 10)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep2
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 20)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep3
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 30)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep4
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 40)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep5
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 50)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep6
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 60)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep7
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 70)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep8
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 80)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep9
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 90)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}
  - name: sleep10
    image: golang:1-bookworm
    command: [ "/bin/bash" ]
    args: [ "-c", "date +%s; sleep $((RANDOM % 100)); date +%s" ]
    resources:
      requests:
        cpu: "0.01"
        memory: "1Mi"
      limits: {}